### ISSUE TITLE
关于TGT

### ISSUE THREAD

**Issue by cyzz523** [anonymous0131/TGTN#2]
你好夏同学，我刚才看了你最新发的TGT代码，我想复现一下，但是一直报错 报错内容如下：tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[13777,8] = -1 is not in [0, 4512)
	 [[node embedding_lookup_2 (defined at C:\Users\admin\anaconda3\envs\GHCF-main\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
请问该如何解决。打扰你啦

**Comment by akaxlh** [comment]
你好，请问能写一下你运行代码的命令行或者模型参数吗？

**Comment by cyzz523** [comment]
期待您的回信





52210313254&nbsp;&nbsp;陈毓哲
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "akaxlh/TGT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月20日(星期四) 晚上11:56
***@***.***&gt;;
抄送:&nbsp;"Spied Yuzhe ***@***.******@***.***&gt;;
主题:&nbsp;Re: [akaxlh/TGT] 关于TGT (Issue #2)





 
你好，请问能写一下你运行代码的命令行或者模型参数吗？

**Comment by cyzz523** [comment]
模型参数我用的你的，没有动过；代码运行直接在pycharm里run的。




52210313254&nbsp;&nbsp;陈毓哲
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "akaxlh/TGT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月20日(星期四) 晚上11:56
***@***.***&gt;;
抄送:&nbsp;"Spied Yuzhe ***@***.******@***.***&gt;;
主题:&nbsp;Re: [akaxlh/TGT] 关于TGT (Issue #2)





 
你好，请问能写一下你运行代码的命令行或者模型参数吗？

**Comment by akaxlh** [comment]
你好，代码里写的默认参数可能不能直接跑出效果，如果不习惯用命令行运行程序，可以尝试在Params.py文件中把参数的默认取值改成readme中How to run the code部分的参数
